[project]
name = "create-collage"
version = "0.1.1"
description = "Program to create a collage of images with optional text overlays."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cairosvg>=2.8.2",
    "pillow>=11.3.0",
]
